# Generated by Django 3.1.5 on 2021-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='latestPrice',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='marketCap',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='previousClose',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week52High',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week52Low',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ytdChange',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tickerSymbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
